### ISSUE TITLE
Calculate a score based on spelling, grammar, and keywords

### ISSUE THREAD

**Issue by torisimon2** [cs481-ekh/s24-gone-phishin#104]
references #40 

Given individual scores based on spelling, grammar, and keywords, calculate a baseline confidence score

Definition of done:
- [x] Implement the algorithm specified in our project proposal.
- [x] Display the confidence score through the extension

**Comment by SorrenMosher** [comment]
Added calculations for computing spelling and grammar scores.
Added the algorithm for the overall confidence score.
Made the confidence score visible through the extension.
Submitted pull request.
[t:65]

**Comment by SorrenMosher** [comment]
Quick bug fix with turning the extension off.
[t:5]
