### ISSUE TITLE
Rework algorithm to account for keyword severity

### ISSUE THREAD

**Issue by torisimon2** [cs481-ekh/s24-gone-phishin#105]
references #40 

Assign keywords a severity score and update the confidence algorithm.

Definition of Done:
- [x] Each keyword is individually assigned a severity score
- [x] An overall keyword score has been formulated
- [x] The confidence algorithm takes keyword score into account

**Comment by SorrenMosher** [comment]
Read through the different sources used to collect our keywords.
[t:25]

**Comment by SorrenMosher** [comment]
Ran the list of keywords through ChatGPT which gave me a good starting point for the weighted keywords.
Went through each keyword and either intuitively adjusted them or did some basic research to determine a good weight.
Updated text file with scores for each keyword, and added 2 additional keywords.
Submitted pr.
[t:95]

**Comment by SorrenMosher** [comment]
Linked the keyword severity scores into the keyword score algorithm.
Submitted pull request.
[t:25]
