### ISSUE TITLE
Set up environment variables

### ISSUE THREAD

**Issue by torisimon2** [cs481-ekh/s24-gone-phishin#106]
references #73 

- [ ] Set up variables for default gmail account (tests can run automatically)

**Comment by kdoster** [comment]
Researched how to auto-login for testing. Need to look more into OAuth2 and Chrome Identity API. Not confident that either will completely automate it.

[t:30]

**Comment by kdoster** [comment]
Tried doing a .env focused route, just accessed my computer credentials instead. Figured that out, and now am getting blocked from signing in due to security issues.

[t:30]

**Comment by kdoster** [comment]
Discovered that the issue is with "Less Secure App Access" which we do not have the option to enable at this time, likely due to account age/activity.

[t:60]

**Comment by kdoster** [comment]
Due to issue mentioned in previous comment, we are aborting this.
