### ISSUE TITLE
Update side panel

### ISSUE THREAD

**Issue by torisimon2** [cs481-ekh/s24-gone-phishin#124]
References #19 

- [x] Side panel does not show email contents
- [x] Side panel shows confidence score
- [ ] Side panel shows spelling, grammar, and keyword partitions

**Comment by kdoster** [comment]
Restructured sidebar to have collapsible sections for spelling and grammar, which involved some restructuring of the div structure.

[t:120]

**Comment by kdoster** [comment]
Added keyword collapsible section and variable font sizes after seeing my work on a smaller screen.

[t:60]

**Comment by kdoster** [comment]
Merged in edits with keywords and formatted them like the spelling and grammar. Also figured out a messy merge conflict.

[t:60]
