### ISSUE TITLE
Create a breakdown of keyword matches

### ISSUE THREAD

**Issue by SorrenMosher** [cs481-ekh/s24-gone-phishin#127]
references #22

## Definition of done
Displays why the keywords that were found in the email are indicative of phishing behavior.

**Comment by Subpoened-peon** [comment]
[t:10] added some reasons for keyword scores in database

**Comment by Subpoened-peon** [comment]
[t:60] finished creating reasons for each keywords appearance on the extension. Added them to the database as well. Worked on getting it to display but will finish either tomorrow or tonight.

**Comment by Subpoened-peon** [comment]
[t:35] Finished adding them to the database array and displaying them inside the tab.
