### ISSUE TITLE
Create the algorithm

### ISSUE THREAD

**Issue by torisimon2** [cs481-ekh/s24-gone-phishin#128]
references #23 

Develop a refined version of the algorithm that more accurately calculates a confidence score representative of spear phishing likelihood.

Definition of Done:
- [x] A new method of determining the spelling score is implemented
- [x] A new method of determining the grammar score is implemented
- [x] A new method of determining the keyword score is implemented

**Comment by SorrenMosher** [comment]
Did some basic research for formulating each algorithm.
Implemented changes for spelling, grammar, and keyword scores.
Submitted pull request.
[t:45]
