### ISSUE TITLE
Add calculated score display

### ISSUE THREAD

**Issue by SorrenMosher** [cs481-ekh/s24-gone-phishin#129]
references #23

- [x] Display confidence score
- [ ] Have an appealing UI to demonstrate severity of score

**Comment by kdoster** [comment]
Moved confidence score to top and gave it color coding depending on score. I plan to make it more appealing/eyecatching, but that might not happen this sprint

[t:30]

**Comment by kdoster** [comment]
Does its job, effort could be better spent elsewhere.
