### ISSUE TITLE
Fix extension needing page refresh on opening another email

### ISSUE THREAD

**Issue by Subpoened-peon** [cs481-ekh/s24-gone-phishin#144]
Our extension sometimes requires the user to refresh the page to scan additional email.

Load the extension and open an email to scan it.
Navigate back to the inbox and open a second email.

Expected behavior
None of the information from the previously scanned email should be retained after going back to the user's inbox.
The extension should be able to scan as many emails in a row without needing a page refresh.

**Comment by SorrenMosher** [comment]
Did basic research on how to listen for changes in web addresses.
Implemented automatic scan upon opening an email.
Fixed the email's results not being flushed after navigating away from the email.
Submitted pull request.
[t:180]

**Comment by SorrenMosher** [comment]
Fixed new bugs introduced:
Scan results are now cleared for all labels and folders in the inbox.
Scan results are no longer inaccurate when swapping between emails rapidly.
[t:110]
