### ISSUE TITLE
Users can see a breakdown of HyperLinks

### ISSUE THREAD

**Issue by Subpoened-peon** [cs481-ekh/s24-gone-phishin#148]
References #22

## Description
Extension reports if there are hyperlinks embedded in the email

Definition of done:
- [x] user can see the number of hyperlinks present in the email
- [x] Users can see what text is part of a hyperlink
- [x] Users can view a description of why the hyperlink factors into the report

**Comment by torisimon2** [comment]
Hyperlinks are fully implemented minus how they factor into the score

[t:65]
