### ISSUE TITLE
Users can see a breakdown of Attachments

### ISSUE THREAD

**Issue by Subpoened-peon** [cs481-ekh/s24-gone-phishin#149]
References #22

## Description
Extension reports whether there are attachments on the email.

Definition of done:
- [x] user can see the number of attachments present in the email
- [x] Users can see the name of the attachments
- [x] Users can view a description of why the attachment factors into the report

**Comment by torisimon2** [comment]
started researching how to count the number of attachments.

[t:30]

**Comment by torisimon2** [comment]
Figured out how to count the number of attachments

[t:70]

**Comment by torisimon2** [comment]
Finished implementing

[t:40]

**Comment by torisimon2** [comment]
Looked at resolving the merge conflicts

[t:15]

**Comment by torisimon2** [comment]
Trying to resolve merge conflicts, something merging from main broke the entire extension in my branch

[t:45]
