### ISSUE TITLE
The limitations of the free language tool does not prevent the extension from running

### ISSUE THREAD

**Issue by Subpoened-peon** [cs481-ekh/s24-gone-phishin#155]
References #44 

The free version of LangaugeTool is limited and as such cannot accommodate larger emails. This should not impede the extension's ability to run, it should instead continue scanning. 

definition of done:
- [x] Scanning continues even after the LangaugeTool limit is reached
- [x] There are no errors related to using the LangaugeTool

**Comment by torisimon2** [comment]
Investigated ways of avoiding the call limit and began implementing

[t:60]

**Comment by torisimon2** [comment]
Working on making calls smaller

[t:70]

**Comment by torisimon2** [comment]
API is no longer affected by length of email and does not throw errors

[t:60]

**Comment by torisimon2** [comment]
API does not throw errors and does not impact other elements

[t:90]

**Comment by torisimon2** [comment]
Fixed the merge conflicts

[t:140]
