### ISSUE TITLE
Rescan button added to the UI

### ISSUE THREAD

**Issue by Subpoened-peon** [cs481-ekh/s24-gone-phishin#156]
References #17

## Description
Extensions sidebar contains a rescan button so users can rescan an opened email.

## Definition of Done
- [x] Button appears in popup
- [ ] Press of button runs rescan

**Comment by kdoster** [comment]
Added button into display as well as clean up elements to adjust for new button. Currently no button functionality.

[t:20]

**Comment by kdoster** [comment]
Restructured document to better facilitate scans. Button now scans.

[t:30]
