### ISSUE TITLE
Rescan button rescans email

### ISSUE THREAD

**Issue by Subpoened-peon** [cs481-ekh/s24-gone-phishin#157]
References #17

## Description
When the user presses the rescan button, it rescans the email that is open.

## Definition of Done
- [ ] Email rescanned upon button push

**Comment by kdoster** [comment]
Tasks I forgot to log time for this sprint:
- Rescan Button
- Help Button
- Practice Pitch
- UI Updates
Estimated time spent: 

[t:720]
