### ISSUE TITLE
Button leads to a separate page

### ISSUE THREAD

**Issue by torisimon2** [cs481-ekh/s24-gone-phishin#170]
references #21 

The user should be able to use the button to navigate to a separate page that includes a more detailed report

**Comment by Subpoened-peon** [comment]
[t:90] got started on the detailedReport page and tried viewing it by directly accessing it through the url and it does appear while also sharing the format of the help page. However, I am unsure if I am getting the correct information from uiDisp due to the current bug we have. Will continue with this until the scanner bug is fixed.

**Comment by Subpoened-peon** [comment]
[t:90] After continuing with the fixes made to the scanner, I noticed some security issues stopping the page from opening and resolved them. Now it is a matter of how the messaging works with when the data from the scanner is available. Currently when I attempt to extract the strings that we have in load analysis, the message for it is sent the moment the page is loaded even before I open the sidebar. Will try and continue work on it tomorrow.

**Comment by Subpoened-peon** [comment]
[t:150] Had to add a button in the popup to allow for the page to be opened in an order proper for data to be scanned and loaded. Currently with the set up it needs to be open before the data can be sent from uiDisp. It has collapsible buttons that appear neatly on the screen and they do indeed display the  information that was scanned. TODO: bring over extension information that has been added, the number of the items found and find a way for the information to be readily available on the first opening. Will discuss with team if I will clean up the sidebar buttons.

**Comment by Subpoened-peon** [comment]
[t:130] Detailed report now has information upon opening and contains information on attachments and the score.
