### ISSUE TITLE
VirusTotal API Research

### ISSUE THREAD

**Issue by kdoster** [cs481-ekh/s24-gone-phishin#190]
References #192 

Investigate VirusTotal as a possible feature to integrate now or in the future

Definition of Done:
- [x] investigate API capabilities
- [x] Compare quality and price of different versions (free vs. paid)
- [x] Investigate practicality of integrating the API now or in the future, detailing benefits and challenges
- [ ] Report to the rest of the team

**Comment by torisimon2** [comment]
Began researching the API

[t:35]

**Comment by torisimon2** [comment]
Finished research and reported findings

[t:20]
