### ISSUE TITLE
Resources Button

### ISSUE THREAD

**Issue by kdoster** [cs481-ekh/s24-gone-phishin#193]
Button that gives more resources to educate with.

## Definition of Done
Button inside of the pop-up brings the user to a new page with some links to additional resources

**Comment by Subpoened-peon** [comment]
[t:10] Created the button on the sidebar

**Comment by Subpoened-peon** [comment]
[t:60] Researched some sites for information a user of Hook Line and Secure might be interested in and added their links to an additional resources page
