### ISSUE TITLE
Update the extension to use the grammar-checker

### ISSUE THREAD

**Issue by Subpoened-peon** [cs481-ekh/s24-gone-phishin#60]
References user story #34 

Updates the extension scanner to use the grammar-checker.

Definition of Done: This task is done when the extension is able to call the API language tool with no errors to achieve grammar checking functionality

**Comment by torisimon2** [comment]
Working on differentiating between grammar and spelling

[t:20]

**Comment by torisimon2** [comment]
Finished differentiation system

[t:20]
