### ISSUE TITLE
Add grammar errors found by scanner to report

### ISSUE THREAD

**Issue by Subpoened-peon** [cs481-ekh/s24-gone-phishin#61]
References user story #34 

Adds the grammatical errors found by the scanner to a report. It will be used to for the final displayed report and the algorithm.

Definition of done:
This task is done when the sidebar correctly displays all relevant information about the grammar mistakes, including number and nature of the mistake, without causing errors, and explains to the user how the grammar factors into the report

**Comment by torisimon2** [comment]
Added all elements to the report. 

[t:45]
