### ISSUE TITLE
Display email elements on page

### ISSUE THREAD

**Issue by kdoster** [cs481-ekh/s24-gone-phishin#66]
References user story #13 

Displays part of the email as proof of email parsing capabilities.

Definition of Done:

- [x] The extension is capable of viewing email contents
- [x] The email contents are retrieved by the extension
- [x] The email contents are displayed by the extension

**Comment by SorrenMosher** [comment]
Added an element to display the email contents on the sidebar.
Added code for parsing an email from the Gmail site.
Added code for displaying the email contents.
Submitted pull request.
[t:120]
