### ISSUE TITLE
Add a panel pop-up for the extension

### ISSUE THREAD

**Issue by Subpoened-peon** [cs481-ekh/s24-gone-phishin#67]
References user story #15

Add a pop-up to build off of for future UI related features.

Definition of Done
- [x] A window opens once the extension activates

**Comment by SorrenMosher** [comment]
Added a window that opens once the extension activates (currently when mail.gmail.com is accessed).
Added minimal formatting and title to the window.
Played around with some tests, but realized the tester needs access to a Gmail account.
I plan to bring this up at our next meeting and talk about possibly incorporating dotenv for environment variables.
Submitted pull request.
[t:180]
