### ISSUE TITLE
Update panel appearance

### ISSUE THREAD

**Issue by Subpoened-peon** [cs481-ekh/s24-gone-phishin#68]
References user story #15

Update panel so that it does not cover other on screen information.

Definition of done:
- [x] The panel is aligned with the right side of the screen.
- [x] The panel squishes the Gmail interface while opened rather than covering it.

**Comment by SorrenMosher** [comment]
Spent majority of time figuring out how to get the Gmail UI to shrink for the side panel.
I attempted to get it to work automatically upon loading the Gmail website but I did not have any luck.
I resorted to adding a button that both pops out the panel and squishes the Gmail interface.
Edited the appearance of the side panel to properly fit in the Gmail interface.
Edited the button to move along with the side panel when it opens or closes.
Submitted pull request.
[t:312]
