### ISSUE TITLE
Update the extension to use the spell-checker

### ISSUE THREAD

**Issue by kdoster** [cs481-ekh/s24-gone-phishin#70]
References user story #33 

Extension has an integrated spell checker

Definition of Done: This task is done when the extension is able to call the API language tool with no errors to achieve spell checking functionality

**Comment by torisimon2** [comment]
Worked on creating a script that could successfully call the LangaugeTool API. It still has several errors but is able to call it.

[t:60]

**Comment by torisimon2** [comment]
Began integrating working code into the extension itself


[t:60]

**Comment by torisimon2** [comment]
More work on integration with the wider application, got it to count the spelling errors in my tests

[t:65]

**Comment by torisimon2** [comment]
Finished

[t:15]
