### ISSUE TITLE
Implement on and off toggle button 

### ISSUE THREAD

**Issue by torisimon2** [cs481-ekh/s24-gone-phishin#98]
references #18 

- [ ] Create toggleable setting for on/off
- [ ] Setting passes created tests

**Comment by kdoster** [comment]
Researched and implemented toggle for on/off. Currently only works when extension is reloaded.

[t:120]

**Comment by kdoster** [comment]
Tried to get eventListeners to work for it to process instantly, no success yet.

[t:30]

**Comment by kdoster** [comment]
Got it all to work properly. Activates based on last setting.

[t:30]
